eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: '8080'

spring:
  cache:
    cacheNames: hazelcast
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8202/
          predicates:
            - Path=/auth/**
        #          filters:
        #            - name: AuthFilter

        -  id: get-data-service
           uri: http://localhost:8209/
           predicates:
             - Path=/get-data/**
#           filters:
#            - name: DataFilter
        -  id: get-data-service2
           uri: http://localhost:8208/
           predicates:
             - Path=/get-data2/**